language: node_js
notifications:
  email: false
before_deploy: npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
env:
  global:
    secure: C1Oid9agNuK3FRazRnzGq8CW6renGREa5Qfxo0NdO/0XPHOfkLUmsu8brqoEI6Pran4PrthjHYrX0OiGrtzZopkMK9elQnWl3GF7m/y2HQ2O426JFAVJnAcc5lQJGL/40Ls/LU4/5OIQew9NqP+XweMFuCZJdKSa8Ubv9pV5Qxh4V/hRThtsQU93SKCbB9FjqMDV1sUrP2OIQxDh00QRwTsDd6Fw8q1UETspY7IREAjQ/TY4QJPDhTHY5QjqNhBzGQ4hZ+AcaN3vlBRcRpgduCG7D1niyZcKCtjKgoklPVLllsrqRltqJarPUaZsppMHOostMAD2GIEvV36SnraE+07dlxfesDxq7cZUBp/2nmhqO5OL9b0C7LhYTsbChFP9PVvhTm7mLYPeCRw5BHureGGRb39eSCOtc0Oy7A1jmioHdsryklYpJTuGLMlX7RIKkPt3daQYJc2KfcBsdIWuN/7zp7rU3QKhots6VCB9a/Q62fV08SLldPuTh0S/72z5ROtSsrD4Rynv+kjtM5s/mskd4K5THk80ZMxIvYV7a5ZHLqDedjWHavvZqS7nvFErSiO1s3UpMMYeVn56y90iI2BECPzDlrGLsEk0gAAAG191oNFpDhvc5sGCF11/UmyXQNJ/g1oRpPtK1frXh0/V0dntWr6qKUFamFyndKd4ocA=
